networks:
  scyther:
    name: scyther

  ferrothorn:
    name: ferrothorn

services:
  database-scyther:
    image: mariadb:latest

    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: scyther
      MARIADB_USER: scyther
      MARIADB_PASSWORD: foobar2000

    networks:
      - scyther

  scyther:
    image: gastrodon/scyther:latest

    deploy:
      restart_policy:
        condition: on-failure

    environment:
      SCYTHER_CONNECTION: scyther:foobar2000@tcp(database-scyther)/scyther

    ports:
      - "3000:8000"

    networks:
      - scyther

    depends_on:
      - database-scyther

  database-ferrothorn:
    image: mariadb:latest

    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: ferrothorn
      MARIADB_USER: ferrothorn
      MARIADB_PASSWORD: foobar2000

    networks:
      - ferrothorn

  ferrothorn:
    image: gastrodon/ferrothorn:latest

    deploy:
      restart_policy:
        condition: on-failure

    environment:
      FERROTHORN_CONNECTION: ferrothorn:foobar2000@tcp(database-ferrothorn)/ferrothorn

    ports:
      - "3001:8000"

    networks:
      - ferrothorn

    depends_on:
      - database-ferrothorn

  database-etl:
    image: mariadb:latest

    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: etl
      MARIADB_USER: etl
      MARIADB_PASSWORD: foobar2000

    networks:
      - etl

    ports:
      - "3306:3306"
